NEW PROVIDER: Oracle Cloud
StackExchange/dnscontrol pull request #1021
Opened 2021-01-16 21:11 UTC by kallsyms

This PR introduces a provider for Oracle Cloud DNS.

OCI DNS API Docs: https://docs.oracle.com/en-us/iaas/api/#/en/dns/20180115/

Few miscellaneous notes from development:
* This currently marks DS records as not supported, despite Oracle saying they are. I'm getting 500s from the API when running the integration tests. I can investigate this further if wanted.
* The API provides only full updates (i.e. replace the entire given rrset/fqdn/zone) or patch (specifying a batch of add/remove operations on the given rrset/rqdn/zone). This PR implements the provider with batched patches per zone.
* The patch API doesn't provide a way to update a single existing record, so this implementation batches a remove then an add operation (mimicking how the console does it).

Addresses #419.

2021-01-18 16:52 UTC, tlimoncelli reviewed
Looks great so far!  I will have a closer look in a few days.

don't worry about adding DS in a separate PR.  It's common to do that.  Get the base working well then augment it.

2021-01-20 04:36 UTC, tlimoncelli requested changes
Great work!  There is very close to being ready to merge.  I just had a few small changes.

By the way... in intergration_test.go, Oracle isn't running the `pager601` tests.  Since the API is slow, and since page size is 100, this test isn't needed. That said, it might be useful to run this test just once to verify functionality (but don't include it in the PR).

2021-01-20 04:36 UTC, tlimoncelli commented on providers/oracle/oracleProvider.go
> +	} else if err != nil && getResp.RawResponse.StatusCode != 404 {
Since the "if" has a return, the "else if" can be an "if".

2021-01-20 04:36 UTC, tlimoncelli commented on providers/oracle/oracleProvider.go
> +	} else {
Since the prior `if` ends with a `return`, this doesn't need to be an `else`.

2021-01-20 04:50 UTC, kallsyms commented
Changes addressed! Just tried the `pager601` test and it creates more than 100 records (so the batching works), but the test hits the 60s deadline before it finishes adding all of them.

2021-01-20 05:16 UTC, tlimoncelli reviewed
Looks great!  Super minor change and we're all done!

(thanks for running the pager601 test.  Yeah, timeouts are expected. At least it worked up until the timeout!)

2021-01-20 05:16 UTC, tlimoncelli commented on providers/oracle/oracleProvider.go
> +
please remove blank line, to group the error check with the related code.

2021-01-20 05:16 UTC, tlimoncelli commented on providers/oracle/oracleProvider.go
> +
please remove blank line, to group the error check with the related code.

2021-01-20 05:16 UTC, tlimoncelli commented on providers/oracle/oracleProvider.go
> +
please remove blank line, to group the error check with the related code.

2021-01-20 05:28 UTC, kallsyms commented
Done!

2021-01-24 20:35 UTC, merged