Update TXT handling for NS1
StackExchange/dnscontrol pull request #1603
Opened 2022-07-05 18:46 UTC by tlimoncelli

Hi @costasd !

Could you please run the integration tests and verify that I didn't break anything?

Thanks!
Tom

2022-07-05 18:49 UTC, costasd commented
Hey @tlimoncelli! 

Apologies for being unresponsive recently, moved places and I'm just settling in. I'll take care of all the open asks in the next couple days.

cheers,
Costas

2022-07-05 19:46 UTC, tlimoncelli commented
No worries.  Thanks for letting me know!

2022-07-14 09:51 UTC, costasd requested changes
Left a suggestion, should be fine as soon as this suggestion is incorporated (can't push to the branch myself)

2022-07-14 09:51 UTC, costasd commented on providers/ns1/ns1Provider.go
> +			err = rec.SetTargetTXTQuotedFields(ans)
```suggestion
			err = rec.SetTargetTXT(ans)
```

ns1's api always adds quotes around strings. Adding them ourselves results to extraneous
quotes finding their way into the record.
ie.
       v := "asdf"
       SetTargetTXT(v) becomes "asdf" on the wire and a record value of `asdf`
       SetTargetTXTQuotedFields(v) becomes "\"asdf\"" on the wire and a record value of `"asdf"`
... which breaks integration on "asdf" != "\"asdf\""


with this fix, LGTM and all tests, manual and integration are succesful!

2022-07-14 21:13 UTC, tlimoncelli commented
I'll be closing this without merging it. See https://github.com/StackExchange/dnscontrol/pull/1567#issuecomment-1184697723 for an explanation.  I do ask that all provider maintainers do 2 things:
1.  Check out the master branch and re-run the integration tests (dnscontrol/integrationTest). (Its a good idea to do this once a year just in case)
2. check your provider to make sure the TXT bug doesn't exist: https://stackexchange.github.io/dnscontrol/testing-txt-records.html

2022-07-20 00:47 UTC, tlimoncelli commented
Closing this.  If you could follow the instructions in https://stackexchange.github.io/dnscontrol/testing-txt-records.html to test for the TXT bug, that would be appreciated.

2022-07-20 00:47 UTC, closed without merging