DOCS: Update how to submit BYO credentials
StackExchange/dnscontrol pull request #2767
Opened 2024-01-05 20:23 UTC by tlimoncelli

* byo-secrets.md: Updates and adds instructions on how to securely submit credentials for use by the project's automated testing.
* writing-providers.md: Adds a better checklist so you know you're done. 
* pr_test.yml: Add comments to make it easier to find sections of the YML

2024-01-05 20:23 UTC, tlimoncelli commented
@cafferata I'd appreciate your proofreading.

2024-01-06 21:01 UTC, cafferata requested changes
> @cafferata I'd appreciate your proofreading.

With all my love! 🤓

2024-01-06 21:01 UTC, cafferata commented on documentation/writing-providers.md
>  2. Verify that [documentation/providers.md](providers.md) no longer shows the provider as "requested"
"Step 16: After the PR is merged" is no longer the current method. This changed with the migration to GitBook.

2024-01-08 03:01 UTC, tlimoncelli commented on documentation/byo-secrets.md
> +To securely send the credentials to the project, use this link: https://transfer.secretoverflow.com/u/tlimoncelli
I'm pretty sure MarkDown makes bare URLs clickable.

2024-01-08 03:39 UTC, tlimoncelli commented on documentation/writing-providers.md
> +  * Post the results as a comment to your PR.
I don't want to overload people at this point.  They've already got so much to get working and debug.

2024-01-08 11:41 UTC, cafferata commented on documentation/byo-secrets.md
> +Github Actions should kick and and run the tests.
Is it true that this suggestion has remained unaddressed?

[Deeplink to: GitHub Actions should kick and and run the tests.](https://docs.dnscontrol.org/~/revisions/e7rW48CevoBtG9K7XvwW/developer-info/byo-secrets#:~:text=GitHub%20Actions%20should%20kick%20and%20and%20run%20the%20tests.)

2024-01-08 11:43 UTC, cafferata commented on documentation/byo-secrets.md
> +Create a new Github issue with a subject "Add PROVIDER to automated tests" where "PROVIDER" is the name of the provider. DO NOT SEND THE CREDENTIALS IN THE GITHUB ISSUE.  Write that you understand th
Is this suggestion maybe missed?

2024-01-08 11:44 UTC, cafferata commented on documentation/byo-secrets.md
> +To securely send the credentials to the project, use this link: https://transfer.secretoverflow.com/u/tlimoncelli
Markdown certainly does that, unfortunately GitBook does not.

2024-01-08 12:02 UTC, cafferata requested changes
The feedback effect already looks great! 🙏 I have one last couple of points that I think you may have missed.

2024-01-08 12:02 UTC, cafferata commented on documentation/writing-providers.md
> +  * (See [Step 7](#step-7-integration-test)).
Is this suggestion maybe missed?

[Deeplink](https://docs.dnscontrol.org/~/revisions/e7rW48CevoBtG9K7XvwW/developer-info/writing-providers#:~:text=Post%20the%20results%20as%20a%20comment%20to%20your%20PR.)

2024-01-08 12:02 UTC, cafferata commented on documentation/writing-providers.md
> +  * `providers/_all/all.go`
Is this suggestion maybe missed?

[Deeplink](https://docs.dnscontrol.org/~/revisions/e7rW48CevoBtG9K7XvwW/developer-info/writing-providers#:~:text=and/or%20updated%3A-,OWNERS,-README.md)

2024-01-08 12:04 UTC, cafferata commented on documentation/writing-providers.md
> +  * Post the results as a comment to your PR.
That can of course be a choice. Will you resolve this GitHub thread?

2024-01-08 12:04 UTC, cafferata commented on documentation/writing-providers.md
>  2. Verify that [documentation/providers.md](providers.md) no longer shows the provider as "requested"
This GitHub thread can be marked as resolved. 👍

2024-01-08 12:05 UTC, cafferata commented on documentation/writing-providers.md
> +WARNING: The integration test requires a DNS zone it can update.  All records
This GitHub thread can be marked as resolved. 👍

2024-01-08 12:05 UTC, cafferata commented on documentation/writing-providers.md
> +  * Remove the provider from the `Requested providers` list (near the end of thedoc) (if needed).
This GitHub thread can be marked as resolved. 👍

2024-01-08 12:05 UTC, cafferata commented on documentation/writing-providers.md
>  Here are some last-minute things to check before you submit your PR.
This GitHub thread can be marked as resolved. 👍

2024-01-08 17:06 UTC, tlimoncelli commented on documentation/byo-secrets.md
> +{% endhint %}
Fixed

2024-01-08 17:07 UTC, tlimoncelli commented
@cafferata  Thanks for all the feedback!  You have an excellent eye for detail!  Much appreciated!

2024-01-08 21:01 UTC, merged