RELEASE: Move some BYOS steps to be standard
StackExchange/dnscontrol pull request #3107
Opened 2024-09-03 13:59 UTC by tlimoncelli

2024-09-11 12:01 UTC, cafferata requested changes

2024-09-11 12:01 UTC, cafferata commented on documentation/writing-providers.md
> +7. [Create an issue (feature request)](https://github.com/StackExchange/dnscontrol/issues/new?title=Add%20label%20for%20PROVIDERNAME) with the text "Please create the GitHub label 'provider-PROVIDERN
**Idea**: Is it an idea to put this more as a checklist for us? Also in a review I feel the need to be able to tick off a checklist.

2024-09-11 12:01 UTC, cafferata commented on documentation/writing-providers.md
> +7. [Create an issue (feature request)](https://github.com/StackExchange/dnscontrol/issues/new?title=Add%20label%20for%20PROVIDERNAME) with the text "Please create the GitHub label 'provider-PROVIDERN
It might make more sense to include the (create the GitHub label 'provider-PROVIDERNAME') request in the original GitHub pull request.

2024-09-12 05:21 UTC, cafferata commented
**Question**: Is this GitHub pull request ready for a (re)review? 🤓

2024-09-12 05:25 UTC, cafferata commented
@tlimoncelli, can you let me know when I can do a review? 🤓

2024-09-12 15:08 UTC, tlimoncelli reviewed
I had to undo the PROVIDERS list change. It is a long string, not a list.

2024-09-13 15:51 UTC, tlimoncelli commented
@cafferata PTAL

2024-09-17 00:54 UTC, merged