Add notifications with Shoutrr
StackExchange/dnscontrol pull request #3215
Opened 2024-11-27 00:47 UTC by hmoffatt

I need to update the documentation, but this seems to work for me.

2024-11-27 10:59 UTC, tlimoncelli commented on pkg/notifications/shoutrrr.go
> +// bonfire notifier for stack exchange internal chat. String is just url with room and token in it
Suggestion: Delete this comment.

2024-12-03 21:04 UTC, kytta commented
I've tested this with Matrix and ntfy, and it works like a charm!

2024-12-03 23:23 UTC, hmoffatt commented
I've added documentation now.

2024-12-04 17:33 UTC, cafferata requested changes

2024-12-04 17:33 UTC, cafferata commented on documentation/notifications.md
> +DNSControl can use many other notification methods via Shoutrrr, such as email (SMTP), Discord, Pushover and others. See the [Shoutrrr documentation](https://containrrr.dev/shoutrrr/v0.8/services/ove
I would like to propose to change this version '0.8' to 'latest'. From the MkDocs generator a redirect takes place to the actual latest version.

```suggestion
DNSControl can use many other notification methods via Shoutrrr, such as email (SMTP), Discord, Pushover and others. See the [Shoutrrr documentation](https://containrrr.dev/shoutrrr/latest/services/overview/) for a list of supported methods and configuration instructions.
```

2024-12-05 13:18 UTC, cafferata approved these changes

2024-12-09 22:14 UTC, tlimoncelli commented on documentation/notifications.md
> +### Others
Suggestion: Move this to the top of the list
```suggestion
### Shoutrrr (email, Discord, Pushover, etc.)
```

2024-12-09 22:17 UTC, tlimoncelli commented
Thank you for adding this!  I didn't know Shoutrr existed.  This should be the way we do all notifications in the future.

2024-12-09 22:17 UTC, merged